In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('telco.csv')
df.head()

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,...,has_internet,has_internet_and_phone,partner_dependents,Start_day,Monthly_charges,Validation,Contract Type,Phone Type,Internet Type,Monthly Tenure
0,0002-ORFBO,Female,0,Yes,Yes,1,1,1,Mailed check,65.6,...,True,True,3,2020-05-03,65.6,1,1 Year,One Line,DSL,9.0
1,0003-MKNFE,Male,0,No,No,2,1,0,Mailed check,59.9,...,True,True,0,2020-05-03,59.9,1,Month-to-Month,Two or More Lines,DSL,9.0
2,0004-TLHLJ,Male,0,No,No,1,2,0,Electronic check,73.9,...,True,True,0,2020-11-03,73.9,1,Month-to-Month,One Line,Fiber Optic,4.0
3,0011-IGKFF,Male,1,Yes,No,1,2,0,Electronic check,98.0,...,True,True,1,2020-02-03,98,1,Month-to-Month,One Line,Fiber Optic,13.0
4,0013-EXCHZ,Female,1,Yes,No,1,2,0,Mailed check,83.9,...,True,True,1,2020-11-03,83.9,1,Month-to-Month,One Line,Fiber Optic,3.0

In [6]:
df.contract_type.value_counts(dropna=False)

0    3876
2    1697
1    1476
Name: contract_type, dtype: int64

In [8]:
df['Contract Type'].value_counts(dropna=False)

3                 6154
Month-to-Month     475
2 Year             226
1 Year             194
Name: Contract Type, dtype: int64

In [13]:
df[df['Contract Type'] == '3']

,customer_id,gender,is_senior_citizen,partner,dependents,phone_service,internet_service,contract_type,payment_type,monthly_charges,...,has_internet,has_internet_and_phone,partner_dependents,Start_day,Monthly_charges,Validation,Contract Type,Phone Type,Internet Type,Monthly Tenure
895,1304-BCCFO,Male,0,Yes,No,1,1,0,Mailed check,70.05,...,True,True,1,2020-06-03,70.05,1,3,One Line,DSL,8.0
896,1304-NECVQ,Female,1,No,No,2,2,0,Electronic check,78.55,...,True,True,0,2021-01-03,78.55,1,3,Two or More Lines,Fiber Optic,2.0
897,1304-SEGFY,Female,0,Yes,No,2,2,2,Electronic check,97.85,...,True,True,1,2015-05-03,97.85,1,3,Two or More Lines,Fiber Optic,70.0
898,1306-RPWXZ,Female,0,No,Yes,1,0,2,Credit card (automatic),20.45,...,False,False,2,2016-12-03,20.45,1,3,One Line,No Internet Service,50.0
899,1307-ATKGB,Male,0,No,No,1,2,0,Electronic check,89.55,...,True,True,0,2019-02-03,89.55,1,3,One Line,Fiber Optic,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7044,NaN,Female,0,No,No,1,1,1,Mailed check,55.15,...,True,True,0,2020-01-03,55.15,1,3,One Line,DSL,13.0
7045,NaN,Male,0,Yes,No,2,2,0,Electronic check,85.10,...,True,True,1,2019-04-03,85.1,1,3,Two or More Lines,Fiber Optic,22.0
7046,NaN,Male,0,No,No,1,1,0,Mailed check,50.30,...,True,True,0,2021-01-03,50.3,1,3,One Line,DSL,2.0
7047,NaN,Male,0,Yes,Yes,1,1,2,Mailed check,67.85,...,True,True,3,2015-06-03,67.85,1,3,One Line,DSL,68.0
7048,NaN,Male,0,Yes,Yes,0,1,2,Electronic check,59.00,...,True,False,3,2015-12-03,59,1,3,No Phone Service,DSL,63.0